feat: added feature to only compile abi json files and wrote test for it
galadd/jags pull request #9
Opened 2023-05-29 20:36 UTC by Destiny-01

2023-05-29 20:37 UTC, Destiny-01 commented
This should close issue #7 and #5

2023-05-30 17:55 UTC, galadd commented
Thank You, Good job👍
For the test, you referenced a file that you did not add. Seems like that it is the reason for the failed test. You can add a test json file to the test directory.  
Do you have a reason for changing the file to be ran? Let me know if there's a particular reason for this. Eventually, I'm going to add the command to `npm run`

2023-05-30 18:09 UTC, galadd requested changes
For the test files. Have small test.json files. Just add its abi to this directory
There should be 3 json files
1. abi with no bytecodes
2. abi with bytecodes 
3. no abi, no bytecodes

2023-05-30 18:14 UTC, galadd commented
> This should close issue #7 and #5

On second thought, it doesn’t close #5 and the reason is that right now, All abi format files have generated code. We want to change that to be only deployed contract

2023-05-31 13:00 UTC, galadd requested changes
Please, look into this. Also, let the test jsons be descriptive of their use. I like notAbi.json!

2023-05-31 13:00 UTC, galadd commented on test/gen.test.js
A way to go about this would be, instead of actually creating a new file for the test, it should simulate it. I suggest you check out [mock-fs] (https://github.com/tschaub/mock-fs) library for this. Then you can just check for a specific content in the simulated file. Tests generating new real files is not ideal. This way we'll be testing for generateJSProgram

2023-05-31 13:00 UTC, galadd commented on src/gen.js
To deal with the issue in the test to also show file creation, I think it's best there's a function writeToFile(file, content). That way, the simulation can be run on this function only

2023-06-24 21:43 UTC, galadd commented
I have made a PR to your branch of this fork. Check it out and merge. I will then update it here

2023-06-24 22:08 UTC, galadd approved these changes

2023-06-24 22:08 UTC, merged